### ISSUE TITLE
use pathlib instead of string paths and glob.glob

### ISSUE THREAD

**Issue by laundmo** [kirakbol/directory-organizer#1]
pathlib can do glob and also handles paths OS independent and allows for easy handling of relative/absolute paths.

**Comment by kirakbol** [comment]
Got it. Had some more stuff to work through to make it work, but I finally did it!

**Comment by laundmo** [comment]
1. with pathlib you shouldn't need seperate windows and linux versions, since relative pathlib paths work the same on both 

2. there is no need to use any os path methods or the glob library anymore, pathlib does it all.

3. youre still storing most paths (all the destinations) as string,l and not as pathlib paths.


i suggest looking into the capabilities of pathlib some more.
